### ISSUE TITLE
 MTM6201-010 -CAL extension for midterm project

### ISSUE THREAD

**Issue by coop0162** [coop0162/mtm6201-midterm#3]
@abhaysharma

I am having difficulties with the alignment of the font with the icons on Page3.html. Additionally, the “express interest” button is not updating its font colour to white main.css code. I am having issues with the display grid of the designer homes section from main.css to index.html. I am attempting to create the desktop version with a media query with main.css to the index.html. However not work and comment the CSS in of the media query.

**Comment by abhaysharma** [comment]
@coop0162 
- Can you clarify the first point if you still need help with "I am having difficulties with the alignment of the font with the icons on Page3.html."
- I see that you were able to update the text color to white for express interest button.
- Issue with the grid, you need to remove the row height from line 66 of you CSS which is making your designer home section overlap the previous one.
- Similar to the Just In section, you need to add grid properties to the .design-homes section.
- Add width 100% to the images in .design-homes section as well.
- Media Query, since you are building mobile-first, your media query needs to be min-width as you are scaling up and want to trigger the styles when the screen size reaches a certain minimum width. You can also try something as below to test the media-query

```
@media (min-width: 700px) {
  body{
    background-color: red;
  }
}
```

**Comment by coop0162** [comment]
@abhaysharma
I am experiencing issues with aligning the font with the icons on Page 3.html .Specifically on lines 45 to 50 the line of text and icon are messy when attempted to CSS code.

.I have attempted to apply CSS to Index.html, but it has resulted in a significant gap between class="design-homes" and class="home-cont" on index.html.

**Comment by abhaysharma** [comment]
@coop0162 you need first to implement the changes I suggested in the previous response, this will help you fix some of the larger issues with the layout.
